---

- include_role:
    name: harrow.base

- name: install rabbitmq-server package
  apt:
    name: rabbitmq-server
    update_cache: true

- name: make data dir on /var/lib/harrow for rabbirmq
  file:
    state: directory
    path: /var/lib/harrow/rabbitmq
    owner: rabbitmq
    group: rabbitmq

- name: remove /var/lib/rabbitmq
  file:
    state: absent
    path: /var/lib/rabbitmq
  become: true

- name: link /var/lib/rabbitmq to /var/lib/harrow/rabbitmq
  file:
    state: link
    dest: /var/lib/rabbitmq
    src: /var/lib/harrow/rabbitmq
    force: true
  notify: restart rabbitmq
  become: true

- lineinfile:
    dest:  /etc/rabbitmq/rabbitmq-env.conf
    line: RABBITMQ_BASE=/var/lib/harrow/rabbitmq
  notify: restart rabbitmq

- systemd:
    name: rabbitmq-server
    state: stopped

- systemd:
    name: rabbitmq-server
    state: started
    enabled: true

- rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- rabbitmq_vhost:
    name: "{{ vhost.name }}"
    state: present
  with_items: "{{ harrow.rabbitmq.virtual_hosts }}"
  loop_control:
    loop_var: vhost

- rabbitmq_user:
    user: "{{ vhost.username }}"
    password: "{{ vhost.password }}"
    vhost: "{{ vhost.name }}"
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    tags: "administrator"
    state: present
  with_items: "{{ harrow.rabbitmq.virtual_hosts }}"
  loop_control:
    loop_var: vhost
