---

# ensure pgbouncer is removed.

- apt:
    name: pgbouncer
    state: absent

- file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/default/pgbouncer
    - /etc/pgbouncer
    - /var/log/pgbouncer/
    - /var/run/pgbouncer
